package com.standard.api.model;
// Generated Apr 20, 2016 2:33:10 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Size;

import org.hibernate.annotations.BatchSize;

/**
 * IwritePolhdr generated by hbm2java
 */
@Entity
@Table(name = "IWRITE_POLHDR")
public class IwritePolhdr implements java.io.Serializable
{

	private IwritePolhdrId id;
	private String prevpolno;
	private String extpolno;
	private String accountType;
	private String paymentPlan;
	private String polstatus;
	private Date inceptionDate;
	private Date expiryDate;
	private Date issueDate;
	private Date origInception;
	private Short daysInsured;
	private Integer clientNo;
	private Integer masterClient;
	private String assuredName1;
	private String assuredName2;
	private String renMethod;
	private String agentType;
	private String agentBranch;
	private Integer agentCode;
	private String marketingGroup;
	private String subagentCode;
	private String latestTrnType;
	private String lob;
	private String uwLock;
	private String uploadStatus;
	private Date dateCreated;
	private String createdBy;
	private Date dateUpdated;
	private String updatedBy;
	private String referralNumber;
	private String approvalNumber;
	private String slipNumber;
	private String originalCurrency;
	private String accountingCurrency;
	private String timeOption;
	private Date cancellationDate;
	private String cancellationReason;
	private String underwritingFlag;
	private String claimsFlag;
	private String acountingFlag;
	private BigDecimal exhangeRate;
	private Integer batchNumber;
	private Date effectiveDate;
	private String entype;
	private Short latestUwYear;
	private Date lastNbrnPostingDate;
	private BigDecimal totalSumInsured;
	private String poljacketNumber;
	private Date currentInception;
	private Date currentExpiry;
	private Integer prBatchNumber;
	private Date postingDatePriorPr;
	private Long iosClientNumber;
	private String cocFlag;
	private String correctProdcode;
	private String riAcctType;
	private String lob2;

	public IwritePolhdr()
	{
	}

	public IwritePolhdr(IwritePolhdrId id)
	{
		this.id = id;
	}

	public IwritePolhdr(IwritePolhdrId id, String prevpolno, String extpolno, String accountType, String paymentPlan, String polstatus, Date inceptionDate, Date expiryDate, Date issueDate, Date origInception, Short daysInsured, Integer clientNo, Integer masterClient, String assuredName1,
			String assuredName2, String renMethod, String agentType, String agentBranch, Integer agentCode, String marketingGroup, String subagentCode, String latestTrnType, String lob, String uwLock, String uploadStatus, Date dateCreated, String createdBy, Date dateUpdated, String updatedBy,
			String referralNumber, String approvalNumber, String slipNumber, String originalCurrency, String accountingCurrency, String timeOption, Date cancellationDate, String cancellationReason, String underwritingFlag, String claimsFlag, String acountingFlag, BigDecimal exhangeRate,
			Integer batchNumber, Date effectiveDate, String entype, Short latestUwYear, Date lastNbrnPostingDate, BigDecimal totalSumInsured, String poljacketNumber, Date currentInception, Date currentExpiry, Integer prBatchNumber, Date postingDatePriorPr, Long iosClientNumber, String cocFlag,
			String correctProdcode, String riAcctType, String lob2)
	{
		this.id = id;
		this.prevpolno = prevpolno;
		this.extpolno = extpolno;
		this.accountType = accountType;
		this.paymentPlan = paymentPlan;
		this.polstatus = polstatus;
		this.inceptionDate = inceptionDate;
		this.expiryDate = expiryDate;
		this.issueDate = issueDate;
		this.origInception = origInception;
		this.daysInsured = daysInsured;
		this.clientNo = clientNo;
		this.masterClient = masterClient;
		this.assuredName1 = assuredName1;
		this.assuredName2 = assuredName2;
		this.renMethod = renMethod;
		this.agentType = agentType;
		this.agentBranch = agentBranch;
		this.agentCode = agentCode;
		this.marketingGroup = marketingGroup;
		this.subagentCode = subagentCode;
		this.latestTrnType = latestTrnType;
		this.lob = lob;
		this.uwLock = uwLock;
		this.uploadStatus = uploadStatus;
		this.dateCreated = dateCreated;
		this.createdBy = createdBy;
		this.dateUpdated = dateUpdated;
		this.updatedBy = updatedBy;
		this.referralNumber = referralNumber;
		this.approvalNumber = approvalNumber;
		this.slipNumber = slipNumber;
		this.originalCurrency = originalCurrency;
		this.accountingCurrency = accountingCurrency;
		this.timeOption = timeOption;
		this.cancellationDate = cancellationDate;
		this.cancellationReason = cancellationReason;
		this.underwritingFlag = underwritingFlag;
		this.claimsFlag = claimsFlag;
		this.acountingFlag = acountingFlag;
		this.exhangeRate = exhangeRate;
		this.batchNumber = batchNumber;
		this.effectiveDate = effectiveDate;
		this.entype = entype;
		this.latestUwYear = latestUwYear;
		this.lastNbrnPostingDate = lastNbrnPostingDate;
		this.totalSumInsured = totalSumInsured;
		this.poljacketNumber = poljacketNumber;
		this.currentInception = currentInception;
		this.currentExpiry = currentExpiry;
		this.prBatchNumber = prBatchNumber;
		this.postingDatePriorPr = postingDatePriorPr;
		this.iosClientNumber = iosClientNumber;
		this.cocFlag = cocFlag;
		this.correctProdcode = correctProdcode;
		this.riAcctType = riAcctType;
		this.lob2 = lob2;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "branchCode", column = @Column(name = "BRANCH_CODE", nullable = false, length = 5)), @AttributeOverride(name = "prodcode", column = @Column(name = "PRODCODE", nullable = false, length = 5)),
			@AttributeOverride(name = "polno", column = @Column(name = "POLNO", nullable = false, precision = 9, scale = 0)) })
	public IwritePolhdrId getId()
	{
		return this.id;
	}

	public void setId(IwritePolhdrId id)
	{
		this.id = id;
	}

	@Column(name = "PREVPOLNO", length = 20)
	public String getPrevpolno()
	{
		return this.prevpolno;
	}

	public void setPrevpolno(String prevpolno)
	{
		this.prevpolno = prevpolno;
	}

	@Column(name = "EXTPOLNO", length = 20)
	public String getExtpolno()
	{
		return this.extpolno;
	}

	public void setExtpolno(String extpolno)
	{
		this.extpolno = extpolno;
	}

	@Column(name = "ACCOUNT_TYPE", length = 1)
	public String getAccountType()
	{
		return this.accountType;
	}

	public void setAccountType(String accountType)
	{
		this.accountType = accountType;
	}

	@Column(name = "PAYMENT_PLAN", length = 1)
	public String getPaymentPlan()
	{
		return this.paymentPlan;
	}

	public void setPaymentPlan(String paymentPlan)
	{
		this.paymentPlan = paymentPlan;
	}

	@Size(max = 2, message = "polstatus invalid length")
	@Column(name = "POLSTATUS", length = 2)
	public String getPolstatus()
	{
		return this.polstatus;
	}

	public void setPolstatus(String polstatus)
	{
		this.polstatus = polstatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "INCEPTION_DATE", length = 7)
	public Date getInceptionDate()
	{
		return this.inceptionDate;
	}

	public void setInceptionDate(Date inceptionDate)
	{
		this.inceptionDate = inceptionDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPIRY_DATE", length = 7)
	public Date getExpiryDate()
	{
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate)
	{
		this.expiryDate = expiryDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ISSUE_DATE", length = 7)
	public Date getIssueDate()
	{
		return this.issueDate;
	}

	public void setIssueDate(Date issueDate)
	{
		this.issueDate = issueDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ORIG_INCEPTION", length = 7)
	public Date getOrigInception()
	{
		return this.origInception;
	}

	public void setOrigInception(Date origInception)
	{
		this.origInception = origInception;
	}

	@Column(name = "DAYS_INSURED", precision = 4, scale = 0)
	public Short getDaysInsured()
	{
		return this.daysInsured;
	}

	public void setDaysInsured(Short daysInsured)
	{
		this.daysInsured = daysInsured;
	}

	@Column(name = "CLIENT_NO", precision = 8, scale = 0)
	public Integer getClientNo()
	{
		return this.clientNo;
	}

	public void setClientNo(Integer clientNo)
	{
		this.clientNo = clientNo;
	}

	@Column(name = "MASTER_CLIENT", precision = 8, scale = 0)
	public Integer getMasterClient()
	{
		return this.masterClient;
	}

	public void setMasterClient(Integer masterClient)
	{
		this.masterClient = masterClient;
	}

	@Column(name = "ASSURED_NAME1", length = 105)
	public String getAssuredName1()
	{
		return this.assuredName1;
	}

	public void setAssuredName1(String assuredName1)
	{
		this.assuredName1 = assuredName1;
	}

	@Column(name = "ASSURED_NAME2", length = 60)
	public String getAssuredName2()
	{
		return this.assuredName2;
	}

	public void setAssuredName2(String assuredName2)
	{
		this.assuredName2 = assuredName2;
	}

	@Column(name = "REN_METHOD", length = 2)
	public String getRenMethod()
	{
		return this.renMethod;
	}

	public void setRenMethod(String renMethod)
	{
		this.renMethod = renMethod;
	}

	@Column(name = "AGENT_TYPE", length = 3)
	public String getAgentType()
	{
		return this.agentType;
	}

	public void setAgentType(String agentType)
	{
		this.agentType = agentType;
	}

	@Column(name = "AGENT_BRANCH", length = 5)
	public String getAgentBranch()
	{
		return this.agentBranch;
	}

	public void setAgentBranch(String agentBranch)
	{
		this.agentBranch = agentBranch;
	}

	@Column(name = "AGENT_CODE", precision = 8, scale = 0)
	public Integer getAgentCode()
	{
		return this.agentCode;
	}

	public void setAgentCode(Integer agentCode)
	{
		this.agentCode = agentCode;
	}

	@Column(name = "MARKETING_GROUP", length = 3)
	public String getMarketingGroup()
	{
		return this.marketingGroup;
	}

	public void setMarketingGroup(String marketingGroup)
	{
		this.marketingGroup = marketingGroup;
	}

	@Column(name = "SUBAGENT_CODE", length = 8)
	public String getSubagentCode()
	{
		return this.subagentCode;
	}

	public void setSubagentCode(String subagentCode)
	{
		this.subagentCode = subagentCode;
	}

	@Column(name = "LATEST_TRN_TYPE", length = 2)
	public String getLatestTrnType()
	{
		return this.latestTrnType;
	}

	public void setLatestTrnType(String latestTrnType)
	{
		this.latestTrnType = latestTrnType;
	}

	@Column(name = "LOB", length = 12)
	public String getLob()
	{
		return this.lob;
	}

	public void setLob(String lob)
	{
		this.lob = lob;
	}

	@Column(name = "UW_LOCK", length = 12)
	public String getUwLock()
	{
		return this.uwLock;
	}

	public void setUwLock(String uwLock)
	{
		this.uwLock = uwLock;
	}

	@Column(name = "UPLOAD_STATUS", length = 1)
	public String getUploadStatus()
	{
		return this.uploadStatus;
	}

	public void setUploadStatus(String uploadStatus)
	{
		this.uploadStatus = uploadStatus;
	}

	@Column(name = "DATE_CREATED")
	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	@Column(name = "CREATED_BY", length = 12)
	public String getCreatedBy()
	{
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy)
	{
		this.createdBy = createdBy;
	}

	@Column(name = "DATE_UPDATED")
	public Date getDateUpdated()
	{
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated)
	{
		this.dateUpdated = dateUpdated;
	}

	@Column(name = "UPDATED_BY", length = 12)
	public String getUpdatedBy()
	{
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy)
	{
		this.updatedBy = updatedBy;
	}

	@Column(name = "REFERRAL_NUMBER", length = 15)
	public String getReferralNumber()
	{
		return this.referralNumber;
	}

	public void setReferralNumber(String referralNumber)
	{
		this.referralNumber = referralNumber;
	}

	@Column(name = "APPROVAL_NUMBER", length = 15)
	public String getApprovalNumber()
	{
		return this.approvalNumber;
	}

	public void setApprovalNumber(String approvalNumber)
	{
		this.approvalNumber = approvalNumber;
	}

	@Column(name = "SLIP_NUMBER", length = 15)
	public String getSlipNumber()
	{
		return this.slipNumber;
	}

	public void setSlipNumber(String slipNumber)
	{
		this.slipNumber = slipNumber;
	}

	@Column(name = "ORIGINAL_CURRENCY", length = 3)
	public String getOriginalCurrency()
	{
		return this.originalCurrency;
	}

	public void setOriginalCurrency(String originalCurrency)
	{
		this.originalCurrency = originalCurrency;
	}

	@Column(name = "ACCOUNTING_CURRENCY", length = 3)
	public String getAccountingCurrency()
	{
		return this.accountingCurrency;
	}

	public void setAccountingCurrency(String accountingCurrency)
	{
		this.accountingCurrency = accountingCurrency;
	}

	@Column(name = "TIME_OPTION", length = 5)
	public String getTimeOption()
	{
		return this.timeOption;
	}

	public void setTimeOption(String timeOption)
	{
		this.timeOption = timeOption;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CANCELLATION_DATE", length = 7)
	public Date getCancellationDate()
	{
		return this.cancellationDate;
	}

	public void setCancellationDate(Date cancellationDate)
	{
		this.cancellationDate = cancellationDate;
	}

	@Column(name = "CANCELLATION_REASON", length = 10)
	public String getCancellationReason()
	{
		return this.cancellationReason;
	}

	public void setCancellationReason(String cancellationReason)
	{
		this.cancellationReason = cancellationReason;
	}

	@Column(name = "UNDERWRITING_FLAG", length = 1)
	public String getUnderwritingFlag()
	{
		return this.underwritingFlag;
	}

	public void setUnderwritingFlag(String underwritingFlag)
	{
		this.underwritingFlag = underwritingFlag;
	}

	@Column(name = "CLAIMS_FLAG", length = 1)
	public String getClaimsFlag()
	{
		return this.claimsFlag;
	}

	public void setClaimsFlag(String claimsFlag)
	{
		this.claimsFlag = claimsFlag;
	}

	@Column(name = "ACOUNTING_FLAG", length = 1)
	public String getAcountingFlag()
	{
		return this.acountingFlag;
	}

	public void setAcountingFlag(String acountingFlag)
	{
		this.acountingFlag = acountingFlag;
	}

	@Column(name = "EXHANGE_RATE", precision = 7, scale = 4)
	public BigDecimal getExhangeRate()
	{
		return this.exhangeRate;
	}

	public void setExhangeRate(BigDecimal exhangeRate)
	{
		this.exhangeRate = exhangeRate;
	}

	@Column(name = "BATCH_NUMBER", precision = 9, scale = 0)
	public Integer getBatchNumber()
	{
		return this.batchNumber;
	}

	public void setBatchNumber(Integer batchNumber)
	{
		this.batchNumber = batchNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EFFECTIVE_DATE", length = 7)
	public Date getEffectiveDate()
	{
		return this.effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate)
	{
		this.effectiveDate = effectiveDate;
	}

	@Column(name = "ENTYPE", length = 5)
	public String getEntype()
	{
		return this.entype;
	}

	public void setEntype(String entype)
	{
		this.entype = entype;
	}

	@Column(name = "LATEST_UW_YEAR", precision = 4, scale = 0)
	public Short getLatestUwYear()
	{
		return this.latestUwYear;
	}

	public void setLatestUwYear(Short latestUwYear)
	{
		this.latestUwYear = latestUwYear;
	}

	@Column(name = "LAST_NBRN_POSTING_DATE")
	public Date getLastNbrnPostingDate()
	{
		return this.lastNbrnPostingDate;
	}

	public void setLastNbrnPostingDate(Date lastNbrnPostingDate)
	{
		this.lastNbrnPostingDate = lastNbrnPostingDate;
	}

	@Column(name = "TOTAL_SUM_INSURED", precision = 20)
	public BigDecimal getTotalSumInsured()
	{
		return this.totalSumInsured;
	}

	public void setTotalSumInsured(BigDecimal totalSumInsured)
	{
		this.totalSumInsured = totalSumInsured;
	}

	@Column(name = "POLJACKET_NUMBER", length = 10)
	public String getPoljacketNumber()
	{
		return this.poljacketNumber;
	}

	public void setPoljacketNumber(String poljacketNumber)
	{
		this.poljacketNumber = poljacketNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CURRENT_INCEPTION", length = 7)
	public Date getCurrentInception()
	{
		return this.currentInception;
	}

	public void setCurrentInception(Date currentInception)
	{
		this.currentInception = currentInception;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CURRENT_EXPIRY", length = 7)
	public Date getCurrentExpiry()
	{
		return this.currentExpiry;
	}

	public void setCurrentExpiry(Date currentExpiry)
	{
		this.currentExpiry = currentExpiry;
	}

	@Column(name = "PR_BATCH_NUMBER", precision = 9, scale = 0)
	public Integer getPrBatchNumber()
	{
		return this.prBatchNumber;
	}

	public void setPrBatchNumber(Integer prBatchNumber)
	{
		this.prBatchNumber = prBatchNumber;
	}

	@Column(name = "POSTING_DATE_PRIOR_PR")
	public Date getPostingDatePriorPr()
	{
		return this.postingDatePriorPr;
	}

	public void setPostingDatePriorPr(Date postingDatePriorPr)
	{
		this.postingDatePriorPr = postingDatePriorPr;
	}

	@Column(name = "IOS_CLIENT_NUMBER", precision = 12, scale = 0)
	public Long getIosClientNumber()
	{
		return this.iosClientNumber;
	}

	public void setIosClientNumber(Long iosClientNumber)
	{
		this.iosClientNumber = iosClientNumber;
	}

	@Column(name = "COC_FLAG", length = 1)
	public String getCocFlag()
	{
		return this.cocFlag;
	}

	public void setCocFlag(String cocFlag)
	{
		this.cocFlag = cocFlag;
	}

	@Column(name = "CORRECT_PRODCODE", length = 5)
	public String getCorrectProdcode()
	{
		return this.correctProdcode;
	}

	public void setCorrectProdcode(String correctProdcode)
	{
		this.correctProdcode = correctProdcode;
	}

	@Column(name = "RI_ACCT_TYPE", length = 2)
	public String getRiAcctType()
	{
		return this.riAcctType;
	}

	public void setRiAcctType(String riAcctType)
	{
		this.riAcctType = riAcctType;
	}

	@Column(name = "LOB2", length = 12)
	public String getLob2()
	{
		return this.lob2;
	}

	public void setLob2(String lob2)
	{
		this.lob2 = lob2;
	}

}
