package com.standard.api.model;
// Generated Apr 20, 2016 2:33:10 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IwritePolhdrId generated by hbm2java
 */
@Embeddable
public class IwritePolhdrId implements java.io.Serializable {

	private String branchCode;
	private String prodcode;
	private int polno;

	public IwritePolhdrId() {
	}

	public IwritePolhdrId(String branchCode, String prodcode, int polno) {
		this.branchCode = branchCode;
		this.prodcode = prodcode;
		this.polno = polno;
	}

	@Column(name = "BRANCH_CODE", nullable = false, length = 5)
	public String getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(String branchCode) {
		this.branchCode = branchCode;
	}

	@Column(name = "PRODCODE", nullable = false, length = 5)
	public String getProdcode() {
		return this.prodcode;
	}

	public void setProdcode(String prodcode) {
		this.prodcode = prodcode;
	}

	@Column(name = "POLNO", nullable = false, precision = 9, scale = 0)
	public int getPolno() {
		return this.polno;
	}

	public void setPolno(int polno) {
		this.polno = polno;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IwritePolhdrId))
			return false;
		IwritePolhdrId castOther = (IwritePolhdrId) other;

		return ((this.getBranchCode() == castOther.getBranchCode()) || (this.getBranchCode() != null
				&& castOther.getBranchCode() != null && this.getBranchCode().equals(castOther.getBranchCode())))
				&& ((this.getProdcode() == castOther.getProdcode()) || (this.getProdcode() != null
						&& castOther.getProdcode() != null && this.getProdcode().equals(castOther.getProdcode())))
				&& (this.getPolno() == castOther.getPolno());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBranchCode() == null ? 0 : this.getBranchCode().hashCode());
		result = 37 * result + (getProdcode() == null ? 0 : this.getProdcode().hashCode());
		result = 37 * result + this.getPolno();
		return result;
	}

}
